POST localhost:9000/webhook/tv/TVB-111/
Content-Type: application/json

{
  "symbol": "ONEUSDT",
  "side": "SELL",
  "type": "LIMIT",
  "price": 0.04,
  "quantity": 125,
  "originOrderId": "test1417",
  "timeFrame": "17",
  "takeProfit": 0.039,
  "stopLoss": 0.041
}

###

POST http://152.42.128.231:9000/webhook/tv/TVB-111/
Content-Type: application/json

{
  "symbol": "ONEUSDT",
  "side": "SELL",
  "type": "LIMIT",
  "price": 0.04,
  "quantity": 125,
  "originOrderId": "test1418",
  "timeFrame": "17",
  "takeProfit": 0.039,
  "stopLoss": 0.041
}

###


POST localhost:9000/webhook/tv/TVB-111/
Content-Type: application/json

{
  "symbol": "ONEUSDT",
  "side": "BUY",
  "type": "LIMIT",
  "price": 0.01,
  "quantity": 500,
  "originOrderId": "test1",
  "timeFrame": "17",
  "takeProfit": 0.02,
  "stopLoss": 0.019
}

###

POST https://1247-5-134-58-242.ngrok-free.app/webhook/tv/TVB-111/
Content-Type: application/json;charset=utf-8

###

GET https://1247-5-134-58-242.ngrok-free.app/
###

POST http://hgstrat.ddns.net/webhook/tv/TVB-111/
Content-Type: application/json

{
  "symbol": "ONEUSDT",
  "side": "SELL",
  "type": "LIMIT",
  "price": 0.01944,
  "quantity": 420.032,
  "originOrderId": "test1301",
  "timeFrame": "17",
  "takeProfit": 0.01906,
  "stopLoss": 0.01984
}

###


#TODO  Account TVB-111, order Order(symbol=ONEUSDT, side=SELL, type=LIMIT, price=0.021, quantity=47.709, originOrderId=ONEUSDT.PT1T1715292960000, goodTillDate=null, timeFrame=1, stopLoss=0.021, takeProfit=0.021, sum=null, state=SIGNAL_RECEIVED, lastUpdate=null, account=null)
POST http://localhost:9000/webhook/tv/TVB-111/
Content-Type: application/json

{
  "symbol": "ONEUSDT",
  "side": "SELL",
  "type": "LIMIT",
  "price": 0.0400,
  "quantity": 125.709,
  "originOrderId": "test1420",
  "timeFrame": "17",
  "takeProfit": 0.04010,
  "stopLoss": 0.03900
}

###
