server:
  port: 9000

spring:
  application:
    name: exchange-bridge
  docker:
    compose:
      enabled: false
      file: docker-compose.yml
  data:
    jpa:
      repositories:
        enabled: true
    jdbc:
      repositories:
        enabled: false
    r2dbc:
      repositories:
        enabled: true
  jpa:
#    database-platform: org.hibernate.community.dialect.SQLiteDialect
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  datasource:
    url: r2dbc:h2:file:///./orderdb;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9020
#    url: jdbc:h2:tcp://localhost/./data/orderdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  r2dbc:
    url: r2dbc:h2:file:///./orderdb;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9021
#  url: jdbc:h2:file:./tmp/test-database
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: true
      settings.web-allow-others: false

hgstrat:
  binance:
    api-key: ${binance-api-key}
    secret-key: ${binance-secret-key}

logging:
  config: classpath:logback-spring.xml
  level:
    web: DEBUG
    webflux: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: TRACE
    org.servlet.mvc.method.annotation.ServletInvocableHandlerMethod: TRACE
    org.springframework.boot.actuate.trace.http.HttpTraceRepository: DEBUG
    org.springframework.http.codec.json: DEBUG
